import type { Scene } from '../types'

// Scenes 3+4: Onboarding experience — deploy + ceremony
export const onboarding: Scene[] = [
  {
    id: 'wallet-deploy',
    title: 'Deploy with your phone',
    duration: 8000,
    steps: [
      { type: 'type', text: 'wallet deploy' },
      { type: 'execute' },
      { type: 'spinner-start', step: 1, total: 8, label: 'Connecting wallet...', delay: 300 },
      {
        type: 'output',
        lines: [{ text: 'Scan QR or tap a link:' }],
        delay: 500,
      },
      { type: 'qr', delay: 300 },
      {
        type: 'output',
        lines: [{ text: '\uD83E\uDD8A MetaMask: tap to open', color: 'dim' }],
        delay: 100,
      },
      {
        type: 'output',
        lines: [{ text: '\uD83C\uDF08 Rainbow:  tap to open', color: 'dim' }],
        delay: 100,
      },
      {
        type: 'output',
        lines: [{ text: '\uD83D\uDD35 Trust:    tap to open', color: 'dim' }],
        delay: 100,
      },
      { type: 'pause', duration: 2000 },
      { type: 'qr-dismiss' },
      { type: 'spinner-complete', step: 1, detail: '0x7745...c7c00 on Base', delay: 300 },
    ],
  },
  {
    id: 'deploy-ceremony',
    title: 'Automated onboarding',
    duration: 8000,
    steps: [
      { type: 'spinner-start', step: 2, total: 8, label: 'Deploying wallet contract...', delay: 300 },
      { type: 'pause', duration: 800 },
      { type: 'spinner-complete', step: 2, detail: '0xA34B...a5dc', delay: 200 },
      { type: 'spinner-start', step: 3, total: 8, label: 'Authorizing machine key...', delay: 200 },
      { type: 'pause', duration: 600 },
      { type: 'spinner-complete', step: 3, detail: '0x9f22...8811', delay: 200 },
      { type: 'spinner-start', step: 4, total: 8, label: 'Setting guardian...', delay: 200 },
      { type: 'pause', duration: 600 },
      { type: 'spinner-complete', step: 4, detail: '0x5be5...f75F', delay: 200 },
      { type: 'spinner-start', step: 5, total: 8, label: 'Configuring policy...', delay: 200 },
      { type: 'pause', duration: 500 },
      { type: 'spinner-complete', step: 5, delay: 200 },
      { type: 'spinner-start', step: 6, total: 8, label: 'Registering agent...', delay: 200 },
      { type: 'pause', duration: 500 },
      { type: 'spinner-complete', step: 6, detail: 'GigaBrain', delay: 200 },
      { type: 'spinner-start', step: 7, total: 8, label: 'Initializing workroom...', delay: 200 },
      { type: 'pause', duration: 400 },
      { type: 'spinner-complete', step: 7, delay: 200 },
      { type: 'spinner-start', step: 8, total: 8, label: 'Starting daemon...', delay: 200 },
      { type: 'pause', duration: 400 },
      { type: 'spinner-complete', step: 8, delay: 200 },
      { type: 'pause', duration: 300 },
      { type: 'output', lines: [{ text: '' }], delay: 100 },
      {
        type: 'output',
        lines: [{ text: '✓ Onboarding complete', prefix: 'success' }],
        delay: 300,
      },
      {
        type: 'tree',
        items: [
          { label: 'Wallet', value: '0xA34B...a5dc' },
          { label: 'Agent', value: 'GigaBrain' },
          { label: 'Service', value: 'intelligence' },
          { label: 'Endpoint', value: 'gigabrain.arc402.xyz' },
          { label: 'Trust', value: '100', last: true },
        ],
        delay: 200,
      },
      { type: 'pause', duration: 1500 },
    ],
  },
]
